/**
 * Every route the app serves, grouped so a suite can pick a slice.
 * Kept beside the tests rather than imported from `app.routes.ts` so a routing
 * mistake shows up as a failing test instead of a silently-shrinking test set.
 */

export const SHELL_ROUTES = [
  '/dashboard/getting-started',
  '/dashboard/basic',
  '/dashboard/analytics',
  '/dashboard/ecommerce',
  '/dashboard/finance',
  '/dashboard/explore',
  '/dashboard/dynamic',

  '/applications/calendar',
  '/applications/messenger',
  '/applications/email/inbox',
  '/applications/email/sent',
  '/applications/email/label/billing',
  '/applications/file-manager',
  '/applications/content-editor',
  '/applications/kanban',
  '/applications/notes',
  '/applications/contacts',
  '/applications/ai-studio',
  '/applications/help-center/home',
  '/applications/help-center/faq',
  '/applications/help-center/guides',
  '/applications/help-center/support',
  '/applications/invoice/list',
  '/applications/invoice/new',
  '/applications/invoice/details/invoice-1',
  '/applications/invoice/edit/invoice-1',
  '/applications/projects',
  '/applications/courses/list',
  '/applications/courses/details/course-1',
  '/applications/courses/builder/course-1',

  '/management/posts/list',
  '/management/posts/new',
  '/management/posts/details/post-1',
  '/management/posts/categories',
  '/management/posts/topics',
  '/management/settings/general',
  '/management/settings/writing',
  '/management/settings/reading',
  '/management/settings/discussion',
  '/management/settings/media',

  '/account/notifications',
  '/account/settings/my-profile',
  '/account/settings/security',
  '/account/settings/notifications',
  '/account/settings/notifications-2',
  '/account/settings/billing',
  '/account/settings/billing-2',
  '/account/settings/sessions',
  '/account/settings/cookie',
  '/account/settings/payment',

  '/user-profile/overview',
  '/user-profile/talent',

  '/widgets/general',
  '/widgets/crypto',
  '/widgets/finance',
  '/widgets/analytics',
  '/cards/general',
  '/cards/users',
  '/prebuilt/skeleton',
  '/prebuilt/notifications',
  '/prebuilt/selects',
  '/prebuilt/dialogs',
  '/datatables/general',
  '/datatables/users',
  '/themes',
  '/pricing/basic',
  '/pricing/membership',
  '/integrations',
  '/service-pages/email-activation',
  '/service-pages/integrations',
  '/content/posts'
] as const;

export const STANDALONE_ROUTES = [
  '/auth/sign-in',
  '/auth/sign-up',
  '/auth/forgot-password',
  '/auth/password-reset',
  '/auth/set-new-password',
  '/auth/create-account',
  '/auth/done',
  '/error/not-found',
  '/error/not-found-2',
  '/error/server-error',
  '/error/server-error-2',
  '/error/forbidden',
  '/error/forbidden-2',
  '/error/maintenance',
  '/onboarding'
] as const;

export const ALL_ROUTES = [...SHELL_ROUTES, ...STANDALONE_ROUTES];

/**
 * A representative slice for the accessibility suite — one page per distinct
 * layout, rather than all 90, so the run stays under a minute.
 */
export const A11Y_ROUTES = [
  '/dashboard/getting-started',
  '/dashboard/basic',
  '/dashboard/explore',
  '/dashboard/dynamic',
  '/applications/calendar',
  '/applications/messenger',
  '/applications/email/inbox',
  '/applications/file-manager',
  '/applications/content-editor',
  '/applications/kanban',
  '/applications/notes',
  '/applications/contacts',
  '/applications/help-center/support',
  '/applications/invoice/list',
  '/applications/invoice/details/invoice-1',
  '/applications/projects',
  '/applications/courses/builder/course-1',
  '/management/posts/list',
  '/management/posts/categories',
  '/management/settings/general',
  '/account/notifications',
  '/account/settings/security',
  '/account/settings/sessions',
  '/account/settings/billing',
  '/user-profile/overview',
  '/cards/general',
  '/cards/users',
  '/prebuilt/skeleton',
  '/datatables/general',
  '/themes',
  '/pricing/basic',
  '/integrations',
  '/content/posts',
  '/auth/sign-in',
  '/auth/create-account',
  '/error/not-found',
  '/error/not-found-2',
  '/onboarding'
] as const;
